// import type { Metadata } from "next";
import { Rubik } from 'next/font/google'
import "./globals.css";
import { Suspense } from 'react';
import LoadingSpinner from './loading';

const rubik = Rubik({ subsets: ['latin'], preload: true })

// export const metadata: Metadata = {
//   title: "NEXT JS ROOT",
//   description: "Generated by create next app",
// };

// export const metadata: Metadata = {
//   title: {
//     // absolute: "",
//     default: "JEFF NEXT PRACTICE DEFAULT",
//     template: "%s | JEFF"
//   },
//   description: "Generated by create next app",
// };

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
      <Suspense fallback={<LoadingSpinner />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
